In [1]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('diabetes.csv')

In [3]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
#Bağımlı ve bağımsız değişkenlerin ayrılması / splitting dependent and independent variables
y = data.Outcome.values
x_data = data.drop(['Outcome'], axis = 1)   #Outcome hariç tüm sütunları al / take all columns except Outcome

In [5]:
from sklearn.model_selection import train_test_split #veri setini train ve test olarak ayırma / splitting dataset as train and test
x_train, x_test, y_train, y_test = train_test_split(x_data,y,test_size = 0.2,random_state=42) #test_size = 0.2 veri setinin %20'sini test için ayırır / splits 20% of the dataset for testing

In [6]:
from sklearn.preprocessing import StandardScaler #veri setini ölçeklendirme /  scaling the dataset
sc = StandardScaler() #standartlaştırma / standardization

In [7]:
xtrain = sc.fit_transform(x_train) #veri setini ölçeklendirme  / scaling the dataset 
xtest = sc.transform(x_test) #veri setini ölçeklendirme

In [8]:
from sklearn.neighbors import KNeighborsClassifier #KNN algoritması / KNN algorithm
knn = KNeighborsClassifier(n_neighbors = 5) #n_neighbors = 5 komşu sayısı / number of neighbors = 5

In [9]:
knn.fit(xtrain,y_train) #modeli eğitme / training the model

KNeighborsClassifier()

In [11]:
yhead = knn.predict(xtest) #tahmin etme  / predicting

In [12]:
yhead

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int64)

In [13]:
new_predict=knn.predict(sc.transform(np.array([[6,148,72,35,0,33.6,0.627,50]])))
new_predict#Yeni bir veri tahmin ettik    / We predicted a new data

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [14]:
new_predict=knn.predict(sc.transform(np.array([[6,148,72,35,0,33.6,0.627,50]])))
new_predict#Yeni bir veri tahmin ettik    / We predicted a new data

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [15]:
import pickle   
with open('scaler.pkl','wb') as file:
    pickle.dump(sc,file)   

In [16]:
with open('model.pkl','wb') as file:
    pickle.dump(knn,file)